// One-shot migration: extracts interpretative items from the legacy questions.json
// (moral_dilemma, paradoxical, interest) and writes seed/interpretative.json with
// alternative impacts stripped out — they will not influence the OCEAN calculation.
//
// Run: node scripts/build_interpretative_seed.js
// Output: seed/interpretative.json

import { readFile, writeFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');

const INTERPRETATIVE_CATEGORIES = new Set(['moral_dilemma', 'paradoxical', 'interest']);

async function main() {
  const legacyRaw = await readFile(join(root, 'seed', 'questions.json'), 'utf-8');
  const legacy = JSON.parse(legacyRaw);

  const items = legacy.questions
    .filter(q => INTERPRETATIVE_CATEGORIES.has(q.category))
    .map(q => ({
      category: q.category,
      text: q.text,
      context: q.context ?? null,
      type: q.type || 'multiple_choice',
      alternatives: (q.alternatives || []).map(a => ({
        text: a.text,
        sort_order: a.sort_order,
      })),
    }));

  const byCategory = items.reduce((acc, q) => {
    acc[q.category] = (acc[q.category] || 0) + 1;
    return acc;
  }, {});

  const output = {
    _comment: 'Generated by scripts/build_interpretative_seed.js — interpretative layer only. These items carry ZERO impact on OCEAN scores.',
    items,
  };

  await writeFile(
    join(root, 'seed', 'interpretative.json'),
    JSON.stringify(output, null, 2),
    'utf-8'
  );

  console.log(`Wrote ${items.length} interpretative items to seed/interpretative.json`);
  console.log('Breakdown:', byCategory);
}

main().catch(err => {
  console.error('Build failed:', err);
  process.exit(1);
});
